version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard 
    - testpackage 
    - varnamelen
    - revive # annoying when you're focusing on developing features and learning
formatters:
  default: all
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax